export interface WhitelistRecipe {
  name: string;
  type: "dish" | "noodle";
  ingredients: string[];
}

export const RECIPE_WHITELIST: WhitelistRecipe[] = [
  { name: "西红柿炒鸡蛋", type: "dish", ingredients: ["西红柿", "鸡蛋"] },
  { name: "青椒炒鸡蛋", type: "dish", ingredients: ["青椒", "鸡蛋"] },
  { name: "韭菜炒鸡蛋", type: "dish", ingredients: ["韭菜", "鸡蛋"] },
  { name: "黄瓜炒鸡蛋", type: "dish", ingredients: ["黄瓜", "鸡蛋"] },
  { name: "土豆丝", type: "dish", ingredients: ["土豆"] },
  { name: "酸辣土豆丝", type: "dish", ingredients: ["土豆", "醋", "辣椒"] },
  { name: "青椒土豆丝", type: "dish", ingredients: ["青椒", "土豆"] },
  { name: "地三鲜", type: "dish", ingredients: ["土豆", "茄子", "青椒"] },
  { name: "红烧茄子", type: "dish", ingredients: ["茄子"] },
  { name: "鱼香茄子", type: "dish", ingredients: ["茄子", "蒜"] },
  { name: "蒜蓉西兰花", type: "dish", ingredients: ["西兰花", "蒜"] },
  { name: "清炒西兰花", type: "dish", ingredients: ["西兰花"] },
  { name: "清炒上海青", type: "dish", ingredients: ["上海青"] },
  { name: "清炒油麦菜", type: "dish", ingredients: ["油麦菜"] },
  { name: "清炒菠菜", type: "dish", ingredients: ["菠菜"] },
  { name: "清炒生菜", type: "dish", ingredients: ["生菜"] },
  { name: "手撕包菜", type: "dish", ingredients: ["包菜"] },
  { name: "醋溜白菜", type: "dish", ingredients: ["白菜", "醋"] },
  { name: "干煸豆角", type: "dish", ingredients: ["豆角"] },
  { name: "豆角炒肉", type: "dish", ingredients: ["豆角", "猪肉"] },
  { name: "青椒肉丝", type: "dish", ingredients: ["青椒", "猪肉"] },
  { name: "鱼香肉丝", type: "dish", ingredients: ["猪肉", "青椒"] },
  { name: "京酱肉丝", type: "dish", ingredients: ["猪肉", "葱"] },
  { name: "木须肉", type: "dish", ingredients: ["猪肉", "鸡蛋", "黄瓜"] },
  { name: "回锅肉", type: "dish", ingredients: ["猪肉", "青椒"] },
  { name: "农家小炒肉", type: "dish", ingredients: ["猪肉", "青椒"] },
  { name: "小炒黄牛肉", type: "dish", ingredients: ["牛肉", "青椒"] },
  { name: "孜然牛肉", type: "dish", ingredients: ["牛肉", "孜然"] },
  { name: "土豆烧牛肉", type: "dish", ingredients: ["土豆", "牛肉"] },
  { name: "红烧牛肉", type: "dish", ingredients: ["牛肉"] },
  { name: "可乐鸡翅", type: "dish", ingredients: ["鸡翅", "可乐"] },
  { name: "红烧鸡翅", type: "dish", ingredients: ["鸡翅"] },
  { name: "宫保鸡丁", type: "dish", ingredients: ["鸡肉", "花生"] },
  { name: "辣子鸡丁", type: "dish", ingredients: ["鸡肉", "辣椒"] },
  { name: "黄焖鸡", type: "dish", ingredients: ["鸡肉", "香菇"] },
  { name: "三杯鸡", type: "dish", ingredients: ["鸡肉", "姜"] },
  { name: "香菇滑鸡", type: "dish", ingredients: ["鸡肉", "香菇"] },
  { name: "青椒鸡丁", type: "dish", ingredients: ["鸡肉", "青椒"] },
  { name: "红烧排骨", type: "dish", ingredients: ["排骨"] },
  { name: "糖醋排骨", type: "dish", ingredients: ["排骨", "醋"] },
  { name: "蒜香排骨", type: "dish", ingredients: ["排骨", "蒜"] },
  { name: "粉蒸排骨", type: "dish", ingredients: ["排骨", "米粉"] },
  { name: "水煮肉片", type: "dish", ingredients: ["猪肉", "豆芽"] },
  { name: "水煮鱼片", type: "dish", ingredients: ["鱼", "豆芽"] },
  { name: "酸菜鱼", type: "dish", ingredients: ["鱼", "酸菜"] },
  { name: "红烧鱼块", type: "dish", ingredients: ["鱼"] },
  { name: "清蒸鲈鱼", type: "dish", ingredients: ["鲈鱼", "姜"] },
  { name: "豆腐烧鱼", type: "dish", ingredients: ["鱼", "豆腐"] },
  { name: "家常豆腐", type: "dish", ingredients: ["豆腐", "青椒"] },
  { name: "麻婆豆腐", type: "dish", ingredients: ["豆腐", "猪肉"] },
  { name: "豆腐炖白菜", type: "dish", ingredients: ["豆腐", "白菜"] },
  { name: "番茄豆腐", type: "dish", ingredients: ["西红柿", "豆腐"] },
  { name: "红烧豆腐", type: "dish", ingredients: ["豆腐"] },
  { name: "干锅花菜", type: "dish", ingredients: ["花菜", "五花肉"] },
  { name: "西红柿炒花菜", type: "dish", ingredients: ["西红柿", "花菜"] },
  { name: "青椒炒杏鲍菇", type: "dish", ingredients: ["青椒", "杏鲍菇"] },
  { name: "蚝油杏鲍菇", type: "dish", ingredients: ["杏鲍菇", "蚝油"] },
  { name: "香菇青菜", type: "dish", ingredients: ["香菇", "青菜"] },
  { name: "蒜苔炒肉", type: "dish", ingredients: ["蒜苔", "猪肉"] },
  { name: "芹菜炒肉", type: "dish", ingredients: ["芹菜", "猪肉"] },
  { name: "西芹百合", type: "dish", ingredients: ["西芹", "百合"] },
  { name: "洋葱炒牛肉", type: "dish", ingredients: ["洋葱", "牛肉"] },
  { name: "洋葱炒鸡蛋", type: "dish", ingredients: ["洋葱", "鸡蛋"] },
  { name: "青椒炒豆干", type: "dish", ingredients: ["青椒", "豆干"] },
  { name: "豆干炒肉丝", type: "dish", ingredients: ["豆干", "猪肉"] },
  { name: "尖椒豆皮", type: "dish", ingredients: ["青椒", "豆皮"] },
  { name: "虎皮青椒", type: "dish", ingredients: ["青椒"] },
  { name: "红烧土豆块", type: "dish", ingredients: ["土豆"] },
  { name: "土豆炖鸡块", type: "dish", ingredients: ["土豆", "鸡肉"] },
  { name: "萝卜炖牛腩", type: "dish", ingredients: ["萝卜", "牛腩"] },
  { name: "番茄牛腩", type: "dish", ingredients: ["西红柿", "牛腩"] },
  { name: "冬瓜丸子汤", type: "dish", ingredients: ["冬瓜", "肉丸"] },
  { name: "紫菜蛋花汤", type: "dish", ingredients: ["紫菜", "鸡蛋"] },
  { name: "西红柿蛋花汤", type: "dish", ingredients: ["西红柿", "鸡蛋"] },
  { name: "菠菜豆腐汤", type: "dish", ingredients: ["菠菜", "豆腐"] },
  { name: "菌菇豆腐汤", type: "dish", ingredients: ["菌菇", "豆腐"] },
  { name: "鸡蛋羹", type: "dish", ingredients: ["鸡蛋"] },
  { name: "蒸南瓜", type: "dish", ingredients: ["南瓜"] },
  { name: "清炒苦瓜", type: "dish", ingredients: ["苦瓜"] },
  { name: "苦瓜炒蛋", type: "dish", ingredients: ["苦瓜", "鸡蛋"] },
  { name: "西红柿鸡蛋面", type: "noodle", ingredients: ["西红柿", "鸡蛋", "面条"] },
  { name: "青菜鸡蛋面", type: "noodle", ingredients: ["青菜", "鸡蛋", "面条"] },
  { name: "青菜肉丝面", type: "noodle", ingredients: ["青菜", "猪肉", "面条"] },
  { name: "榨菜肉丝面", type: "noodle", ingredients: ["榨菜", "猪肉", "面条"] },
  { name: "雪菜肉丝面", type: "noodle", ingredients: ["雪菜", "猪肉", "面条"] },
  { name: "葱油拌面", type: "noodle", ingredients: ["葱", "面条"] },
  { name: "阳春面", type: "noodle", ingredients: ["葱", "面条"] },
  { name: "炸酱面", type: "noodle", ingredients: ["猪肉", "黄酱", "面条"] },
  { name: "打卤面", type: "noodle", ingredients: ["鸡蛋", "木耳", "面条"] },
  { name: "酸汤面", type: "noodle", ingredients: ["醋", "辣椒", "面条"] },
  { name: "牛肉面", type: "noodle", ingredients: ["牛肉", "面条"] },
  { name: "红烧牛肉面", type: "noodle", ingredients: ["牛肉", "面条"] },
  { name: "鸡丝面", type: "noodle", ingredients: ["鸡肉", "面条"] },
  { name: "三鲜面", type: "noodle", ingredients: ["虾", "鸡蛋", "面条"] },
  { name: "香菇鸡汤面", type: "noodle", ingredients: ["香菇", "鸡肉", "面条"] },
  { name: "番茄牛肉面", type: "noodle", ingredients: ["西红柿", "牛肉", "面条"] },
  { name: "茄丁肉末面", type: "noodle", ingredients: ["茄子", "猪肉", "面条"] },
  { name: "麻酱拌面", type: "noodle", ingredients: ["芝麻酱", "面条"] },
  { name: "刀削面", type: "noodle", ingredients: ["面条"] },
  { name: "热干面", type: "noodle", ingredients: ["芝麻酱", "面条"] }
];
